name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libsqlite3-dev

    - name: Setup GoogleTest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: Build Project
      run: |
        mkdir -p obj
        mkdir -p bin
        make all

    - name: Run Tests
      run: make test
